services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  apiauthgatewayservice:
    build:
      context: ./ApiAuthGatewayService
      dockerfile: Dockerfile
    container_name: apiauthgatewayservice-talentoapp
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SHARED_SECRET: ${AUTH_SHARED_SECRET}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      COMPANY_REQUEST_SERVICE_URL: ${COMPANY_REQUEST_SERVICE_URL}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
      JOB_POST_SERVICE_URL: ${JOB_POST_SERVICE_URL}
      APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL}
      ANALYSIS_SERVICE_URL: ${ANALYSIS_SERVICE_URL}

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: userservice-talentoapp
    restart: unless-stopped
    ports:
      - "8070:8070"
    depends_on:
      db:
        condition: service_healthy
    environment:
      AUTH_SHARED_SECRET: ${AUTH_SHARED_SECRET}
      SPRING_DATASOURCE_URL: ${USER_SVC_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      COMPANY_REQUEST_SERVICE_URL: ${COMPANY_REQUEST_SERVICE_URL}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
      JOB_POST_SERVICE_URL: ${JOB_POST_SERVICE_URL}
      APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL}
      ANALYSIS_SERVICE_URL: ${ANALYSIS_SERVICE_URL}

  companyrequestservice:
    build:
      context: ./CompanyRequestService
      dockerfile: Dockerfile
    container_name: companyrequestservice-talentoapp
    restart: unless-stopped
    ports:
      - "8060:8060"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${CR_SVC_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
      JOB_POST_SERVICE_URL: ${JOB_POST_SERVICE_URL}
      APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL}
      ANALYSIS_SERVICE_URL: ${ANALYSIS_SERVICE_URL}

  companyservice:
    build:
      context: ./CompanyService
      dockerfile: Dockerfile
    container_name: companyservice-talentoapp
    restart: unless-stopped
    ports:
      - "8050:8050"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${CR_SVC_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      COMPANY_REQUEST_SERVICE_URL: ${COMPANY_REQUEST_SERVICE_URL}
      JOB_POST_SERVICE_URL: ${JOB_POST_SERVICE_URL}
      APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL}
      ANALYSIS_SERVICE_URL: ${ANALYSIS_SERVICE_URL}

  jobpostservice:
    build:
      context: ./JobPostService
      dockerfile: Dockerfile
    container_name: jobpostservice-talentoapp
    restart: unless-stopped
    ports:
      - "8040:8040"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${CR_SVC_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      COMPANY_REQUEST_SERVICE_URL: ${COMPANY_REQUEST_SERVICE_URL}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
      APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL}
      ANALYSIS_SERVICE_URL: ${ANALYSIS_SERVICE_URL}

  applicationservice:
    build:
      context: ./ApplicationService
      dockerfile: Dockerfile
    container_name: applicationservice-talentoapp
    restart: unless-stopped
    ports:
      - "8030:8030"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${CR_SVC_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      COMPANY_REQUEST_SERVICE_URL: ${COMPANY_REQUEST_SERVICE_URL}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
      JOB_POST_SERVICE_URL: ${JOB_POST_SERVICE_URL}
      ANALYSIS_SERVICE_URL: ${ANALYSIS_SERVICE_URL}

  analysisservice:
    build:
      context: ./AnalisysService
      dockerfile: Dockerfile
    container_name: analysisservice-talentoapp
    restart: unless-stopped
    ports:
      - "8020:8020"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8020
      SPRING_DATASOURCE_URL: ${CR_SVC_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      COMPANY_REQUEST_SERVICE_URL: ${COMPANY_REQUEST_SERVICE_URL}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
      JOB_POST_SERVICE_URL: ${JOB_POST_SERVICE_URL}
      APPLICATION_SERVICE_URL: ${APPLICATION_SERVICE_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

volumes:
  pgdata: